<a href="https://colab.research.google.com/github/marinapor/Mis-tareas/blob/master/Ejercicios3_Marina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

UNO

In [1]:
import numpy as np
la_version = np.version.version
print (la_version)

1.17.5


DOS


In [2]:
import numpy as np
vector_uno = np.random.randint(0,300,30)
print (vector_uno)

[199  65 116 170  92  88 138  69  47 125  92 298  37  77 265 296 158 265
 218 271 143 192 249 232 127 196 209 175 157 286]


TRES

In [3]:
import numpy as np
multiplos_de3 = vector_uno % 3 == 0
print (multiplos_de3)

[False False False False False False  True  True False False False False
 False False False False False False False False False  True  True False
 False False False False False False]


CUATRO


In [4]:
filtro_multiplosD3 = vector_uno [multiplos_de3]
print (filtro_multiplosD3)

[138  69 192 249]


CINCO

In [5]:
matrizBooleana = multiplos_de3.reshape (3,10)
print (matrizBooleana)

[[False False False False False False  True  True False False]
 [False False False False False False False False False False]
 [False  True  True False False False False False False False]]


SEIS

In [6]:
arreglo1=np.arange(4,14)
arreglo2=np.arange(7,17)
repetidos = []
for i in arreglo1:
  for j in arreglo2:
    if i == j :
      repetidos.append(i)
print (repetidos)

[7, 8, 9, 10, 11, 12, 13]


SIETE


In [7]:
import numpy as np
vector_uno = np.random.randint(0,300,30)
vector_uno.sort()
print(vector_uno)
media = np.mean (vector_uno)
promedio = np.around(media, decimals=0)
print (promedio)
valores_medios = []
for i in vector_uno:
  if i >= promedio-2 and i <= promedio+2:
    valores_medios.append(i)
print (valores_medios)    




[  0   2   3   6  11  14  16  33  35  50  51  56  58  60  73  90 111 129
 134 142 151 154 160 173 196 198 209 289 291 295]
106.0
[]


OCHO

In [8]:
import numpy as np
mi_vector = np.arange (0, 12, dtype=float)
redondeo = np.around (mi_vector/3.5 , decimals=3)
print(redondeo)

[0.    0.286 0.571 0.857 1.143 1.429 1.714 2.    2.286 2.571 2.857 3.143]


NUEVE

In [9]:
import numpy as np
matriz3D = np.random.randint (0, 8, (3,3))
print (matriz3D)

[[5 2 2]
 [0 6 3]
 [5 0 2]]


DIEZ

In [10]:
import numpy as np
mi_arreglo = np.array([1,2,0,0,4])
print ( np.where (mi_arreglo != 0) )

(array([0, 1, 4]),)


ONCE

In [11]:
import numpy as np
un_arreglo = np.random.randint(0,200,30)
print (un_arreglo)
print (np.mean (un_arreglo) )

[150 192 120 176  72  26  11 194  58 117 182   9 191  47  51 144 173  51
  82  84  23  15 171 157  69 110  98  87 125 159]
104.8


DOCE

In [12]:
import numpy as np
matriz_base = np.zeros((6,6))
matriz_base[0,:] = [1,1,1,1,1,1]
matriz_base[5,:] = [1,1,1,1,1,1]
matriz_base[:,0] = [1,1,1,1,1,1]
matriz_base[:,5] = [1,1,1,1,1,1]
print (matriz_base)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


TRECE

In [13]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

CATORCE

In [14]:
import numpy as np
una_matriz = np.random.randint( 0,20, (5,5) )
elementos_cambiados = np.arange (4)
una_matriz [elementos_cambiados, elementos_cambiados+1]=[1,2,3,4]
print (una_matriz)  

[[ 1  1  8 17 18]
 [13 18  2 11  2]
 [ 7  0  5  3 17]
 [ 6 16  2 11  4]
 [ 5  6 14 14 19]]


QUINCE

In [15]:
import numpy as np
matriz_primera = np.random.randint(0,50,(5,5))
print (matriz_primera)
minimo = matriz_primera.min()
maximo = matriz_primera.max()
matriz_normal = (matriz_primera - minimo)/(maximo - minimo)
print ( matriz_normal)
    



[[38 33 23  7 31]
 [49  2 20 10 13]
 [12  1 14 33  7]
 [48 47  6  5 19]
 [25 47 12 49 41]]
[[0.77083333 0.66666667 0.45833333 0.125      0.625     ]
 [1.         0.02083333 0.39583333 0.1875     0.25      ]
 [0.22916667 0.         0.27083333 0.66666667 0.125     ]
 [0.97916667 0.95833333 0.10416667 0.08333333 0.375     ]
 [0.5        0.95833333 0.22916667 1.         0.83333333]]


SECCION DOS: PANDAS

UNO


In [16]:
import pandas as pd
print('pandas: {}'.format(pd.__version__))


pandas: 0.25.3


In [17]:
pip show pandas


Name: pandas
Version: 0.25.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /usr/local/lib/python3.6/dist-packages
Requires: python-dateutil, numpy, pytz
Required-by: xarray, vega-datasets, statsmodels, stable-baselines, sklearn-pandas, seaborn, pymc3, plotnine, pandas-profiling, pandas-gbq, pandas-datareader, mlxtend, mizani, magenta, gspread-dataframe, google-colab, fix-yahoo-finance, featuretools, fbprophet, fastai, cufflinks, altair


DOS

In [2]:
import pandas as pd
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'], 'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3], 'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
tabla_animales = pd.DataFrame (data=data, index=labels)
tabla_animales

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

TRES

In [19]:
import pandas as pd
import numpy as np

tabla_animales.describe(include ="all")

animal       age     visits priority
count      10  8.000000  10.000000       10
unique      3       NaN        NaN        2
top       cat       NaN        NaN       no
freq        4       NaN        NaN        6
mean      NaN  3.437500   1.900000      NaN
std       NaN  2.007797   0.875595      NaN
min       NaN  0.500000   1.000000      NaN
25%       NaN  2.375000   1.000000      NaN
50%       NaN  3.000000   2.000000      NaN
75%       NaN  4.625000   2.750000      NaN
max       NaN  7.000000   3.000000      NaN

CUATRO

In [20]:
import pandas as pd
import numpy as np
tabla_animales.head (n=3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

CINCO

In [4]:
import pandas as pd
import numpy as np
tabla_animales = tabla_animales.rename(columns= {"animal":"Animal", "age":"Edad", "visits":"Visitas", "priority":"Prioridad"} )
tabla_animales

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

SEIS

In [22]:
import pandas as pd
import numpy as np
tabla_animales.iloc[:,[0,1]]

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

SIETE

In [23]:
import pandas as pd
import numpy as np
tabla_animales.loc[ tabla_animales ["Visitas"] >=3 ]

Animal  Edad  Visitas Prioridad
b    cat   3.0        3       yes
d    dog   NaN        3       yes
f    cat   2.0        3        no

OCHO

In [24]:
import pandas as pd
import numpy as np
sin_edad = tabla_animales[tabla_animales.Edad.isnull()]
sin_edad

Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes

NUEVE

In [7]:
import pandas as pd
import numpy as np

entreDosyCuatro = tabla_animales[ tabla_animales.Edad.isin ([2, 2.5, 3]) ]
entreDosyCuatro



Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no

DIEZ

In [26]:
import pandas as pd
import numpy as np
tabla_animales["Visitas"].sum()


19

ONCE

In [27]:
import pandas as pd
import numpy as np
tabla_animales.groupby("Animal").size()

Animal
cat      4
dog      4
snake    2
dtype: int64

DOCE

In [28]:
import pandas as pd
import numpy as np
tabla_animales = tabla_animales.replace({"yes":True , "no":False})
tabla_animales

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

TRECE

In [29]:
import pandas as pd
import numpy as np 
ordenPorEdad = tabla_animales.sort_values('Edad', ascending = False )
ordenPorEdad

Animal  Edad  Visitas  Prioridad
i    dog   7.0        2      False
e    dog   5.0        2      False
g  snake   4.5        1      False
b    cat   3.0        3       True
j    dog   3.0        1      False
a    cat   2.5        1       True
f    cat   2.0        3      False
c  snake   0.5        2      False
d    dog   NaN        3       True
h    cat   NaN        1       True

In [31]:

ordenPorVisitas = tabla_animales.sort_values ('Visitas')
ordenPorVisitas

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
g  snake   4.5        1      False
h    cat   NaN        1       True
j    dog   3.0        1      False
c  snake   0.5        2      False
e    dog   5.0        2      False
i    dog   7.0        2      False
b    cat   3.0        3       True
d    dog   NaN        3       True
f    cat   2.0        3      False

CATORCE

In [33]:
import pandas as pd
import numpy as np
tabla_animales.groupby( ["Animal","Visitas"] ).mean()

Edad  Prioridad
Animal Visitas                 
cat    1         2.5        1.0
       3         2.5        0.5
dog    1         3.0        0.0
       2         6.0        0.0
       3         NaN        1.0
snake  1         4.5        0.0
       2         0.5        0.0